### ISSUE TITLE
Unnecessary "fl" in the search window with the Horizon theme

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Japan/geeklog-japan#7]
![horizonbug](https://cloud.githubusercontent.com/assets/2015377/23630150/4d330d48-02fd-11e7-8145-6053db76e658.png)

**Comment by ivywe** [comment]
font link error when using etag="true" in functions.php

functions.phpで、CSSのファイル統合をしてしまうと、CSSからのパスが変わるので、fontへのリンクエラーが起きていました。UIkitのCSSを書き換えればよいのですが、他のDenimにもあわせてfalseにします。
